services:
  db:
    image: postgres
    restart: always
    ports:
      - 5000:5432
    environment:
      POSTGRES_USER: recommender
      POSTGRES_PASSWORD: "***"
      POSTGRES_DB: recommender
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
